domain: pinout.xyz
analytics_id: UA-69846516-1 
base_url: /pinout/
resource_url: /resources/
url_suffix:
urls:
  GND: ground
featured:
- d3-camera-mezzanine
- grove-seeed-sensor-mezzanine
- aero-core-2
- ethernet-mezzanine
overlays:
- ground
- i2c
- spi
- uart
- d3-camera-mezzanine
- grove-seeed-sensor-mezzanine
- aero-core-2
- ethernet-mezzanine
- arrow-audio-mezzanine
- mipi-adapter-mezzanine-aistarvision
- stm32-sensor-mezzanine-board
- uart-serial-mezzanine